create table public.orphanages(
    id integer not null generated by default as identity,
    name varchar(255) not null,
    latitude numeric not null,
    longitude numeric not null,
    about text not null,
    instructions text not null,
    opening_hours text not null,
    open_on_weekends boolean not null default false,
    CONSTRAINT pk_orphanage PRIMARY KEY (id)
);

create table public.images(
    id integer not null generated by default as identity,
    path varchar(255) not null,
    orphanage_id integer null,
    CONSTRAINT pk_images PRIMARY KEY (id),
    CONSTRAINT uk_path UNIQUE (path),
    CONSTRAINT fk_orphanage_image FOREIGN KEY (orphanage_id) REFERENCES orphanages(id)
);
